<?php
// Configurações do banco de dados
define('DB_HOST', 'localhost');
define('DB_USER', 'jgzoxaxy_1');
define('DB_PASS', 'lemile87');
define('DB_NAME', 'jgzoxaxy_1');

// Configurações do sistema
define('UPLOAD_DIR', 'uploads/');
define('MAX_FILE_SIZE', 20000000); // 20MB

// Tratamento de erros
error_reporting(E_ALL);
ini_set('display_errors', 1);

try {
    // Criar conexão
        $conn = new mysqli(DB_HOST, DB_USER, DB_PASS);
            
                // Verificar conexão
                    if ($conn->connect_error) {
                            throw new Exception("Conexão falhou: " . $conn->connect_error);
                                }

                                    // Criar banco de dados se não existir
                                        $conn->query("CREATE DATABASE IF NOT EXISTS " . DB_NAME);
                                            
                                                // Selecionar banco de dados
                                                    $conn->select_db(DB_NAME);
                                                        
                                                            // Definir charset
                                                                $conn->set_charset("utf8mb4");
                                                                    
                                                                        // Criar tabelas se não existirem
                                                                            $tables = [
                                                                                    "CREATE TABLE IF NOT EXISTS users (
                                                                                                id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                            username VARCHAR(50) NOT NULL UNIQUE,
                                                                                                                        password VARCHAR(255) NOT NULL,
                                                                                                                                    is_admin BOOLEAN DEFAULT FALSE,
                                                                                                                                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                                                                                                                                                        )",
                                                                                                                                                                
                                                                                                                                                                        "CREATE TABLE IF NOT EXISTS media (
                                                                                                                                                                                    id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                                                                                                                title VARCHAR(255) NOT NULL,
                                                                                                                                                                                                            description TEXT,
                                                                                                                                                                                                                        filename VARCHAR(255) NOT NULL,
                                                                                                                                                                                                                                    type ENUM('image', 'video') NOT NULL,
                                                                                                                                                                                                                                                user_id INT,
                                                                                                                                                                                                                                                            upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                                                                                                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                                                                                                                                                                                                                                                                                )",
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                "CREATE TABLE IF NOT EXISTS reports (
                                                                                                                                                                                                                                                                                                            id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                        media_id INT,
                                                                                                                                                                                                                                                                                                                                    user_id INT,
                                                                                                                                                                                                                                                                                                                                                reason TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                            report_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                                                                                                                                                                                                                                                                                                                                        status ENUM('pendente', 'analisado', 'resolvido') DEFAULT 'pendente',
                                                                                                                                                                                                                                                                                                                                                                                    FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                                                                                                                                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                                                                                                                                                                                                                                                                                                                                                                                                        )"
                                                                                                                                                                                                                                                                                                                                                                                                            ];
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    // Executar criação das tabelas
                                                                                                                                                                                                                                                                                                                                                                                                                        foreach ($tables as $sql) {
                                                                                                                                                                                                                                                                                                                                                                                                                                if (!$conn->query($sql)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Exception("Erro ao criar tabela: " . $conn->error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Criar diretório de uploads se não existir
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!file_exists(UPLOAD_DIR)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mkdir(UPLOAD_DIR, 0777, true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Verificar permissões do diretório
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!is_writable(UPLOAD_DIR)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                chmod(UPLOAD_DIR, 0777);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        die("Erro de configuração: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>