<?php
session_start();
require_once 'config.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $username = $_POST['username'];
        $password = $_POST['password'];

            try {
                    // Verificar usuário
                            $stmt = $conn->prepare("SELECT id, username, password, is_admin FROM users WHERE username = ?");
                                    $stmt->bind_param("s", $username);
                                            $stmt->execute();
                                                    $result = $stmt->get_result();

                                                            if ($result->num_rows === 1) {
                                                                        $user = $result->fetch_assoc();
                                                                                    
                                                                                                // Verificar senha
                                                                                                            if (password_verify($password, $user['password'])) {
                                                                                                                            // Login bem sucedido
                                                                                                                                            $_SESSION['user_id'] = $user['id'];
                                                                                                                                                            $_SESSION['username'] = $user['username'];
                                                                                                                                                                            $_SESSION['is_admin'] = $user['is_admin'];
                                                                                                                                                                                            
                                                                                                                                                                                                            // Redirecionar baseado no tipo de usuário
                                                                                                                                                                                                                            if ($user['is_admin']) {
                                                                                                                                                                                                                                                header('Location: admin/dashboard.php');
                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                    header('Location: index.php');
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                    exit();
                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                $_SESSION['error'] = 'Senha incorreta';
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                $_SESSION['error'] = 'Usuário não encontrado';
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                            } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                    $_SESSION['error'] = 'Erro ao fazer login';
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                            header('Location: login.php');
                                                                                                                                                                                                                                                                                                                                                                                                                exit();
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                ?>